// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    partial class AnimalShelterApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Age");

                    b.Property<string>("Color");

                    b.Property<string>("Name");

                    b.Property<string>("Species");

                    b.HasKey("PetId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            PetId = 1,
                            Age = "7",
                            Color = "black",
                            Name = "Fred",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 2,
                            Age = "3",
                            Color = "white",
                            Name = "Chubs",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 3,
                            Age = "5",
                            Color = "black/white",
                            Name = "Teddy",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 4,
                            Age = "10",
                            Color = "tan",
                            Name = "Billy",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 5,
                            Age = "3",
                            Color = "black/white",
                            Name = "Snoopy",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 6,
                            Age = "6",
                            Color = "brown",
                            Name = "Bear",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 7,
                            Age = "11",
                            Color = "gray",
                            Name = "Hulk",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 8,
                            Age = "12",
                            Color = "black",
                            Name = "Medusa",
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 9,
                            Age = "7",
                            Color = "black/brown",
                            Name = "Hercules",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 10,
                            Age = "9",
                            Color = "gray",
                            Name = "Pythagrous",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
